Add a check to make sure that nothing is printed to stderr
Currently, on this branch, the following is being printed to stderr when
running RuboCop:

```
rubocop-rspec_rails extension supports plugin, specify `plugins: rubocop-rspec_rails` instead of `require: rubocop-rspec_rails` in /home/runner/work/runger_style/runger_style/rulesets/rspec_rails.yml.
For more information, see https://docs.rubocop.org/rubocop/plugin_migration_guide.html.
```

We want this to cause CI to fail.

diff --git a/.github/workflows/ruby.yml b/.github/workflows/ruby.yml
--- a/.github/workflows/ruby.yml
+++ b/.github/workflows/ruby.yml
@@ -22,7 +22,13 @@ jobs:
         gem install bundler -v 2.1.4
         bundle install --jobs 4 --retry 3
     - name: Run RuboCop
-      run: bin/rubocop --format clang
+      run: bin/rubocop --format clang --color 2> >(tee /tmp/rubocop_stderr >&2)
+    - name: Check that RuboCop didn't write anything to stderr
+      run: |
+        if [[ -s /tmp/rubocop_stderr ]] ; then
+          echo "Error: stderr was not empty" >&2
+          exit 1
+        fi
     - name: Run RSpec tests
       run: bin/rspec --format progress
     - name: Ensure alpha version
